[package]
name = "torgap-sig-cli-rust"
version = "0.5.6"
authors = ["Frank Denis <github@pureftpd.org>", "Daniel Rangel <daniel@rangel.in>", "ChristopherA@LifeWithAlacrity.com"]
description = "minisign with support for Tor hidden service keys"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "cryptography"]
keywords = ["command-line", "sign", "publickey", "cryptography", "minisign", "Tor"]
repository = "https://github.com/BlockchainCommons/torgap-sig-cli-rust"

[dependencies]
base64 = "0.13"
clap = "2.33"
hex= "0.4.2"
minisign = { git = "https://github.com/BlockchainCommons/torgap-sig.git", branch = "master" }


[target.'cfg(any(windows, unix))'.dependencies]
dirs = "3.0"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
